<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/barrel.glb --transform
-->

<script>
  import { T, useCamera } from '@threlte/core'
  import { AnimatedSpriteMaterial, Billboard, PositionalAudio, useCursor, useGltf } from '@threlte/extras'
  import { interactivity } from '@threlte/extras';
	import { Attractor, AutoColliders, RigidBody, useRapier } from '@threlte/rapier';
	import { clamp } from 'three/src/math/MathUtils.js';
  import { base } from '$app/paths';
  
  let { fallback, error, children, ref = $bindable(), on_done, ...props } = $props()
  let { rigidBodyObjects } = useRapier();

  
  interactivity();
  const gltf = useGltf(`${base}/model/barrel.glb`);
  
  let exploded = $state(false)
  let audio = $state(new Audio());
  let self_rigid_body = $state();
  

  let force = 5;

  const explode = () => {
    if (exploded) {
      return;
    }
    audio.play();
    exploded = true;
    let pos = self_rigid_body.translation();
    for (let [handle, obj] of rigidBodyObjects) {
      if (handle == self_rigid_body.handle) {
        continue;
      }
      let rb = obj.userData.rigidBody;
      let rb_pos = rb.translation();
      let diff_x = rb_pos.x - pos.x;
      let diff_y = rb_pos.y - pos.y;
      let diff_z = rb_pos.z - pos.z;

      let dist = Math.sqrt(diff_x * diff_x + diff_y * diff_y + diff_z * diff_z);
      let force_adj = clamp(1 - dist / 10, 0, 1) * force;

      rb.applyImpulse(
        {x: diff_x * force_adj, y: diff_y * force_adj, z: diff_z * force_adj},
        true
      );
    }
  }
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <RigidBody bind:rigidBody={self_rigid_body} type={exploded ? 'fixed' : 'dynamic'}>
        <PositionalAudio
          autoplay={false}
          volume={3}
          bind:ref={audio}
          src="{base}/sound/explode_1.wav"
        />
        <AutoColliders shape={'convexHull'}>
          <T.Mesh
            geometry={gltf.nodes.Barrel_LOD_1_0.geometry}
            material={gltf.materials['Scene_-_Root']}
            scale={[0.5, 0.5, 0.8]}
            visible={!exploded}
            onclick={(event) => {
              explode();
            }}
          />
        </AutoColliders>
        {#if exploded}
          <Billboard>
            <T.Mesh rotation={[0, 0, Math.PI / 2]} scale={[5, 5, 5]}>
              <AnimatedSpriteMaterial textureUrl="{base}/texture/explosion-sheet.png" totalFrames={45} onend={()=>on_done()} loop={false} />
              <T.PlaneGeometry />
            </T.Mesh>
          </Billboard>
          {/if}
      </RigidBody>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
