<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /Users/kolcrooks/Downloads/crate.glb
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf, PositionalAudio } from '@threlte/extras';
	import { AutoColliders, Collider, RigidBody } from '@threlte/rapier';
	import { clamp } from 'three/src/math/MathUtils.js';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/model/crate.glb');

  let audios = $state([new Audio(), new Audio(), new Audio(), new Audio(), new Audio(), new Audio()]);

  const fireSound = (event) => {
    let audio = audios[Math.floor(Math.random() * audios.length)]
    audio?.stop?.()
    audio?.play?.()
  }

  let audio_is = [0,1,2,3,4,5];


</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.18}>
			<RigidBody type={'dynamic'}  oncollisionenter={fireSound}>
        {#each audio_is as i}
          <PositionalAudio
          autoplay={false}
          bind:ref={audios[i]}
          src={`/sound/flesh_impact_hard${i + 1}.wav`}
        />
        {/each}

      
				<AutoColliders contactForceEventThreshold={30} restitution={1} shape={'cuboid'}>
					<T.Mesh
						geometry={gltf.nodes.Object_3.geometry}
						material={gltf.materials.initialShadingGroup}
					/>
				</AutoColliders>
			</RigidBody>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
